steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/hackathon-mentor-bot:$COMMIT_SHA', '.']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/hackathon-mentor-bot:$COMMIT_SHA']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'hackathon-mentor-bot'
      - '--image'
      - 'gcr.io/$PROJECT_ID/hackathon-mentor-bot:$COMMIT_SHA'
      - '--region'
      - 'asia-northeast1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
      - '--set-env-vars'
      - 'SLACK_BOT_TOKEN=${_SLACK_BOT_TOKEN},SLACK_SIGNING_SECRET=${_SLACK_SIGNING_SECRET},GOOGLE_CLOUD_PROJECT=$PROJECT_ID,MENTOR_CHANNEL_ID=${_MENTOR_CHANNEL_ID}'

# Makefileからの実行時に使用する代替設定値
substitutions:
  _SLACK_BOT_TOKEN: 'your-slack-bot-token'
  _SLACK_SIGNING_SECRET: 'your-slack-signing-secret' 
  _MENTOR_CHANNEL_ID: 'your-mentor-channel-id'

images:
  - 'gcr.io/$PROJECT_ID/hackathon-mentor-bot:$COMMIT_SHA'