export const QUESTION_TEMPLATES = {
  技術的な問題: {
    API関連: {
      description: 'REST API、GraphQL、外部API統合の問題',
      fields: [
        {
          id: 'api_name',
          label: '使用API名',
          placeholder: 'GitHub API v4, OpenAI API, Stripe API',
          required: true,
        },
        {
          id: 'endpoint',
          label: 'エンドポイント',
          placeholder: 'POST /api/users, GET /v1/models',
          required: true,
        },
        {
          id: 'request_content',
          label: 'リクエスト内容',
          type: 'textarea',
          placeholder: 'ヘッダー、ボディ、パラメータなど',
          required: true,
        },
        {
          id: 'error_response',
          label: 'エラーレスポンス',
          type: 'textarea',
          placeholder: 'エラーメッセージ、ステータスコード',
          required: true,
        },
        {
          id: 'expected_result',
          label: '期待する結果',
          placeholder: 'ユーザー情報を取得したい',
          required: true,
        },
      ],
    },
    フロントエンド: {
      description: 'React、Vue、HTML/CSS、JavaScript の問題',
      fields: [
        {
          id: 'framework',
          label: 'フレームワーク',
          placeholder: 'React 18.2.0, Vue 3.3, Vanilla JS',
          required: true,
        },
        {
          id: 'expected_behavior',
          label: '期待する動作',
          type: 'textarea',
          placeholder: 'ボタンクリックでモーダルが表示される',
          required: true,
        },
        {
          id: 'actual_behavior',
          label: '実際の動作',
          type: 'textarea',
          placeholder: '何も起こらない、エラーが出る',
          required: true,
        },
        {
          id: 'browser_info',
          label: 'ブラウザ情報',
          placeholder: 'Chrome 120, Safari 17, Firefox 121',
          required: false,
        },
        {
          id: 'console_errors',
          label: 'コンソールエラー',
          type: 'textarea',
          placeholder: 'F12で確認できるエラーメッセージ',
          required: false,
        },
      ],
    },
    バックエンド: {
      description: 'サーバーサイド、データベース、認証の問題',
      fields: [
        {
          id: 'tech_stack',
          label: '技術スタック',
          placeholder: 'Node.js + Express, Python + Django',
          required: true,
        },
        {
          id: 'function_purpose',
          label: '実装したい機能',
          type: 'textarea',
          placeholder: 'ユーザー登録、ファイルアップロード',
          required: true,
        },
        {
          id: 'current_issue',
          label: '現在の問題',
          type: 'textarea',
          placeholder: 'サーバーエラー、データが保存されない',
          required: true,
        },
        {
          id: 'server_logs',
          label: 'サーバーログ',
          type: 'textarea',
          placeholder: 'エラーログやスタックトレース',
          required: false,
        },
      ],
    },
    データベース: {
      description: 'SQL、NoSQL、クエリ、パフォーマンスの問題',
      fields: [
        {
          id: 'db_type',
          label: 'データベース種類',
          placeholder: 'PostgreSQL 15, MongoDB 6.0, MySQL 8.0',
          required: true,
        },
        {
          id: 'query_content',
          label: 'クエリ内容',
          type: 'textarea',
          placeholder: 'SELECT、INSERT、UPDATEなどのクエリ',
          required: true,
        },
        {
          id: 'error_message',
          label: 'エラーメッセージ',
          type: 'textarea',
          placeholder: 'データベースから返されるエラー',
          required: true,
        },
        {
          id: 'table_structure',
          label: 'テーブル構造',
          type: 'textarea',
          placeholder: 'CREATE TABLEの内容や関連テーブル',
          required: false,
        },
        {
          id: 'expected_result',
          label: '想定する結果',
          placeholder: 'ユーザー一覧を日付順で取得',
          required: true,
        },
      ],
    },
    'デプロイ・インフラ': {
      description: 'AWS、Docker、CI/CD、サーバー設定の問題',
      fields: [
        {
          id: 'platform',
          label: 'プラットフォーム',
          placeholder: 'AWS、Vercel、Heroku、GCP',
          required: true,
        },
        {
          id: 'deployment_method',
          label: 'デプロイ方法',
          placeholder: 'Docker、GitHub Actions、手動デプロイ',
          required: true,
        },
        {
          id: 'error_logs',
          label: 'エラーログ',
          type: 'textarea',
          placeholder: 'デプロイ時またはランタイムエラー',
          required: true,
        },
        {
          id: 'config_files',
          label: '設定ファイル',
          type: 'textarea',
          placeholder: 'Dockerfile、package.json、環境変数',
          required: false,
        },
      ],
    },
  },
  'デザイン・UI/UX': {
    レイアウト問題: {
      description: 'CSS、レスポンシブ、グリッドレイアウトの問題',
      fields: [
        {
          id: 'css_framework',
          label: 'CSSフレームワーク',
          placeholder: 'Tailwind CSS、Bootstrap、CSS Grid',
          required: true,
        },
        {
          id: 'desired_layout',
          label: '実現したいレイアウト',
          type: 'textarea',
          placeholder: '3カラムレイアウト、カード型一覧',
          required: true,
        },
        {
          id: 'current_problem',
          label: '現在の問題',
          type: 'textarea',
          placeholder: 'レスポンシブが効かない、位置がずれる',
          required: true,
        },
        {
          id: 'target_devices',
          label: 'ターゲットデバイス',
          placeholder: 'モバイル・タブレット・デスクトップ',
          required: true,
        },
        {
          id: 'reference_design',
          label: '参考デザイン',
          placeholder: 'Figma URL、参考サイトURL',
          required: false,
        },
      ],
    },
    'UI コンポーネント': {
      description: 'ボタン、フォーム、モーダル等の UI コンポーネント',
      fields: [
        {
          id: 'component_type',
          label: 'コンポーネント種類',
          placeholder: 'ボタン、フォーム、モーダル、ナビゲーション',
          required: true,
        },
        {
          id: 'design_requirements',
          label: 'デザイン要件',
          type: 'textarea',
          placeholder: 'ホバー効果、アニメーション、色指定',
          required: true,
        },
        {
          id: 'interaction_issue',
          label: 'インタラクションの問題',
          type: 'textarea',
          placeholder: 'クリックが効かない、アニメーションがガクつく',
          required: true,
        },
        {
          id: 'browser_compatibility',
          label: 'ブラウザ対応',
          placeholder: '対応が必要なブラウザ',
          required: false,
        },
      ],
    },
    'UX・ユーザビリティ': {
      description: 'ユーザー体験、アクセシビリティ、パフォーマンス',
      fields: [
        {
          id: 'user_scenario',
          label: 'ユーザーシナリオ',
          type: 'textarea',
          placeholder: 'ユーザーがどのような流れで操作するか',
          required: true,
        },
        {
          id: 'ux_issue',
          label: 'UXの問題',
          type: 'textarea',
          placeholder: 'わかりにくい、使いにくい、迷ってしまう',
          required: true,
        },
        {
          id: 'improvement_goal',
          label: '改善したい点',
          type: 'textarea',
          placeholder: 'ユーザーが迷わず目的を達成できるように',
          required: true,
        },
        {
          id: 'target_users',
          label: 'ターゲットユーザー',
          placeholder: '初心者、エンジニア、一般ユーザー',
          required: false,
        },
      ],
    },
  },
  'ビジネス・企画': {
    機能企画: {
      description: '新機能のアイデア、要件定義、優先度決めの相談',
      fields: [
        {
          id: 'feature_concept',
          label: '機能のコンセプト',
          type: 'textarea',
          placeholder: 'どのような機能を作りたいか',
          required: true,
        },
        {
          id: 'target_users',
          label: 'ターゲットユーザー',
          placeholder: '誰のための機能か',
          required: true,
        },
        {
          id: 'problem_to_solve',
          label: '解決したい課題',
          type: 'textarea',
          placeholder: 'ユーザーのどんな困りごとを解決するか',
          required: true,
        },
        {
          id: 'success_metrics',
          label: '成功指標',
          placeholder: 'どうなったら成功と言えるか',
          required: false,
        },
        {
          id: 'constraints',
          label: '制約条件',
          type: 'textarea',
          placeholder: '時間、予算、技術的制約など',
          required: false,
        },
      ],
    },
    マーケティング戦略: {
      description: 'ユーザー獲得、プロモーション、分析の相談',
      fields: [
        {
          id: 'product_overview',
          label: 'プロダクト概要',
          type: 'textarea',
          placeholder: 'どのようなサービス・アプリか',
          required: true,
        },
        {
          id: 'marketing_goal',
          label: 'マーケティング目標',
          type: 'textarea',
          placeholder: 'ユーザー獲得、認知向上、収益化',
          required: true,
        },
        {
          id: 'target_market',
          label: 'ターゲット市場',
          placeholder: '年齢層、職業、興味関心など',
          required: true,
        },
        {
          id: 'current_challenge',
          label: '現在の課題',
          type: 'textarea',
          placeholder: 'ユーザーが増えない、認知されないなど',
          required: true,
        },
        {
          id: 'budget_timeframe',
          label: '予算・期間',
          placeholder: '使える予算と実施期間',
          required: false,
        },
      ],
    },
    収益モデル: {
      description: 'マネタイズ、価格設定、ビジネスモデルの相談',
      fields: [
        {
          id: 'current_model',
          label: '現在のビジネスモデル',
          type: 'textarea',
          placeholder: 'サブスク、広告、手数料など',
          required: true,
        },
        {
          id: 'revenue_challenge',
          label: '収益面の課題',
          type: 'textarea',
          placeholder: '収益が上がらない、価格設定に迷う',
          required: true,
        },
        {
          id: 'value_proposition',
          label: '提供価値',
          type: 'textarea',
          placeholder: 'ユーザーにどんな価値を提供しているか',
          required: true,
        },
        {
          id: 'competitor_analysis',
          label: '競合分析',
          type: 'textarea',
          placeholder: '競合の価格やモデル',
          required: false,
        },
      ],
    },
  },
  その他: {
    '学習・キャリア相談': {
      description: '技術学習、キャリアパス、スキルアップの相談',
      fields: [
        {
          id: 'current_skills',
          label: '現在のスキル',
          type: 'textarea',
          placeholder: 'プログラミング言語、フレームワーク等',
          required: true,
        },
        {
          id: 'learning_goal',
          label: '学習目標',
          type: 'textarea',
          placeholder: '身につけたいスキル、なりたい姿',
          required: true,
        },
        {
          id: 'current_challenge',
          label: '現在の課題',
          type: 'textarea',
          placeholder: '学習で困っていること、悩み',
          required: true,
        },
        {
          id: 'timeframe',
          label: '学習期間',
          placeholder: '3ヶ月、半年、1年など',
          required: false,
        },
        {
          id: 'learning_style',
          label: '学習スタイル',
          placeholder: '独学、スクール、実践重視など',
          required: false,
        },
      ],
    },
    'チーム・協働': {
      description: 'チームワーク、コミュニケーション、プロジェクト管理',
      fields: [
        {
          id: 'team_structure',
          label: 'チーム構成',
          placeholder: 'エンジニア3名、デザイナー1名など',
          required: true,
        },
        {
          id: 'collaboration_issue',
          label: '協働の課題',
          type: 'textarea',
          placeholder: 'コミュニケーション、進捗管理、役割分担',
          required: true,
        },
        {
          id: 'project_phase',
          label: 'プロジェクトフェーズ',
          placeholder: '企画、開発、テスト、リリース',
          required: true,
        },
        {
          id: 'tools_used',
          label: '使用ツール',
          placeholder: 'Slack、Notion、GitHub、Figma',
          required: false,
        },
        {
          id: 'deadline',
          label: '期限・スケジュール',
          placeholder: 'ハッカソン終了まで残り2日',
          required: false,
        },
      ],
    },
    一般的な質問: {
      description: '上記カテゴリに当てはまらない質問',
      fields: [
        {
          id: 'question_topic',
          label: '質問の分野',
          placeholder: 'プログラミング、デザイン、ビジネス等',
          required: true,
        },
        {
          id: 'specific_question',
          label: '具体的な質問',
          type: 'textarea',
          placeholder: '詳細な質問内容',
          required: true,
        },
        {
          id: 'context',
          label: '背景・状況',
          type: 'textarea',
          placeholder: 'なぜこの質問をするに至ったか',
          required: true,
        },
        {
          id: 'expected_advice',
          label: '期待するアドバイス',
          placeholder: '具体的な手順、おすすめツール等',
          required: false,
        },
      ],
    },
  },
};
